------------ENCRYPTION------------------

-----CRYPT_GEN_RANDOM
--This function returns a cryptographic, randomly-generated number, generated by the Crypto API (CAPI).

/*CRYPT_GEN_RANDOM ( length [ , seed ] ) */

SELECT CRYPT_GEN_RANDOM(50) ;

SELECT CRYPT_GEN_RANDOM(4, 0x25F18060) ;

---RAND ( [ seed ] )  
--Returns a pseudo-random float value from 0 through 1, exclusive.

SELECT RAND(100), RAND(), RAND()

DECLARE @counter SMALLINT;  
SET @counter = 1;  
WHILE @counter < 5  
   BEGIN  
      SELECT RAND() Random_Number  
      SET @counter = @counter + 1  
   END;  
GO

---HASHBYTES
/*HASHBYTES ( '<algorithm>', { @input | 'input' } )  
  
<algorithm>::= MD2 | MD4 | MD5 | SHA | SHA1 | SHA2_256 | SHA2_512*/

DECLARE @HashThis NVARCHAR(32);  
SET @HashThis = CONVERT(NVARCHAR(32),'dslfdkjLK85kldhnv$n000#knf');  
SELECT HASHBYTES('SHA2_256', @HashThis);

CREATE TABLE dbo.Test1 (c1 NVARCHAR(32));  
INSERT dbo.Test1 VALUES ('This is a test.');  
INSERT dbo.Test1 VALUES ('This is test 2.');  
SELECT HASHBYTES('SHA2_256', c1) FROM dbo.Test1;

/*
CREATE TABLE Contents.ContentTypes (
	ContentTypeID int NOT NULL CONSTRAINT PK_ContentTypes_ContentTypeID PRIMARY KEY IDENTITY(1, 1),
	ContentType nvarchar(40) NOT NULL CONSTRAINT CHK_ContentTypes_ContentType CHECK (ContentType IN ('Video', 'PPT', 'Other'))
)
GO

ALTER TABLE Contents.ContentTypes
DROP CONSTRAINT CHK_ContentTypes_ContentType*/