USE SQLDay15


		/*CREATE THE TABLE FOR STORING CUSTOMER INFO*/

CREATE TABLE Customers(
CustomerID INT ,
CustomerName VARCHAR(20),
AccountNo INT
FOREIGN KEY (AccountNo) REFERENCES BankDetails(AccountNo)
PRIMARY KEY(CustomerName,AccountNO)

)

		/*CREATE THE TABLE FOR STORING BANKDETAILS INFO*/

CREATE TABLE BankDetails(
AccountNo INT PRIMARY KEY,
TotalAmount FLOAT 
)

		/*CREATE THE TABLE FOR STORING DEPOSIT INFO*/

CREATE TABLE Deposit(
DepositNo INT PRIMARY KEY IDENTITY(1,1),
AccountNo INT,

DepositeAmount FLOAT,
DepositDate DATE
FOREIGN KEY (AccountNo) REFERENCES BankDetails(AccountNo)

)
		/*CREATE THE TABLE FOR STORING WITHDRAWL INFO*/

CREATE TABLE Withdrawl(
WithdrawlNo INT PRIMARY KEY IDENTITY(1,1),
AccountNo INT,

WithdrawlAmount FLOAT,
WithdrawlDate DATE
FOREIGN KEY (AccountNo) REFERENCES BankDetails(AccountNo)

)

			/*ALL THE TABLES WHICH ARE USED IN THE TASK*/

select * from Customers
select * from BankDetails
select * from Deposit
select * from Withdrawl



				/*TRIGGER FOR THE EVENT OF  AFTER INSERT ON THE TABLE DEPOSIT*/

	CREATE OR ALTER TRIGGER ForDeposit
	ON Deposit
	AFTER INSERT
	AS
	BEGIN
	BEGIN TRANSACTION
	UPDATE BankDetails
	SET TotalAmount=TotalAmount+(SELECT DepositeAmount FROM inserted) WHERE AccountNo=(SELECT AccountNo FROM INSERTED)	
	DECLARE @Min FLOAT
	SET @Min=(SELECT DepositeAmount FROM inserted)
	IF(@Min<500)		--CHECKING THE CONDITION THAT DEPOSIT AMOUNT SHOULD BE GREATER THAN 500
	BEGIN
	ROLLBACK TRANSACTION 
	END
	ELSE
	BEGIN
	COMMIT TRANSACTION
	END
	END


				/*TRIGGER FOR THE EVENT OF  AFTER INSERT ON THE TABLE WITHDRAWL*/

	CREATE OR ALTER TRIGGER ForWithdrawl
	ON Withdrawl
	AFTER INSERT
	AS
	BEGIN
	BEGIN TRANSACTION 
	UPDATE BankDetails
	SET TotalAmount=TotalAmount-(SELECT WithdrawlAmount FROM inserted) WHERE AccountNo=(SELECT AccountNo FROM INSERTED)
	DECLARE @Min FLOAT
	SET @Min=(SELECT WithdrawlAmount FROM inserted)
	IF(@Min<500)			--CHECKING THE CONDITION THAT WITHDRAW AMOUNT SHOULD BE GREATER THAN 500
	BEGIN
	ROLLBACK TRANSACTION 
	END
	ELSE
	BEGIN
	COMMIT TRANSACTION
	END
	END

					/*SAMPLE DEPOSIT AND WITHDRAW INPUT*/


INSERT INTO Withdrawl VALUES(105,100,'1998-03-06')
INSERT INTO Deposit VALUES(105,100,'1998-03-06')


