CREATE DATABASE StudentReport

CREATE TABLE STUDENT(
	STD_ID INT NOT NULL CONSTRAINT pkStudentId PRIMARY KEY(STD_ID),
	STD_NAME VARCHAR(50) NOT NULL

)
GO

CREATE TABLE FACULTY (
		F_ID INT NOT NULL CONSTRAINT pkFacultyID  PRIMARY KEY(F_ID),
		F_NAME VARCHAR(50)  
)
GO

CREATE TABLE LEARNING 
(
		STD_ID INT CONSTRAINT fkForignKEyStd_ID FOREIGN KEY  REFERENCES dbo.STUDENT(STD_ID),
		F_ID INT CONSTRAINT fkForignKEYF_ID FOREIGN KEY REFERENCES dbo.FACULTY(F_ID)
)

SElect * FROM STUDENT
SElect * FROM FACULTY
SElect * FROM LEARNING
NAME
SELECT STD_NAME ,F_NAME FROM STUDENT JOIN FACULTY ON (STUDENT.STD_ID=FACULTY.F_ID) JOIN LEARNING ON(LEARNING.STD_ID=FACULTY.F_ID)

SELECT STD_NAME,F_NAME FROM STUDENT JOIN LEARNING ON STUDENT.STD_ID=LEARNING.STD_ID  JOIN FACULTY ON FACULTY.F_ID=LEARNING.F_ID   

SELECT COUNT(STD_ID),F_NAME FROM FACULTY  JOIN LEARNING ON FACULTY.F_ID=LEARNING.F_ID GROUP BY F_NAME


SELECT F_NAME FROM FACULTY JOIN LEARNING ON FACULTY.F_ID=LEARNING.F_ID GROUP BY F_NAME HAVING COUNT(STD_ID)>2

WITH F_NAME_CTE(F_NAME,STD_ID)
AS 
(
	SELECT F_NAME,STD_ID FROM FACULTY JOIN LEARNING ON FACULTY.F_ID=LEARNING.F_ID
)
SELECT F_NAME FROM F_NAME_CTE GROUP BY F_NAME HAVING COUNT(STD_ID)>2

CREATE PROCEDURE dbo.addData
AS
BEGIN
DECLARE @JSON NVARCHAR(MAX); 
SET @JSON=N'[
		{"Name:"D","FNAME":"Y"},
		{"Name":"c","FNAME":"Z"}
		]';

DECLARE add_data CURSOR  

SELECT * FROM OPENJSON(@JSON)
WITH (
	STD_NAME VARCHAR(50)  '$.NAME',
	FNAME VARCHAR(50) '$.FNAME'
);
    
OPEN add_data

FETCH NEXT FROM add_data;



/*SELECT * FROM OPENJSON(@JSON)
WITH (
	STD_NAME VARCHAR(50)  '$.NAME',
	FNAME VARCHAR(50) '$.FNAME'
);*/



	
