CREATE DATABASE StudentReport

CREATE TABLE STUDENT(
	STD_ID INT NOT NULL CONSTRAINT pkStudentId PRIMARY KEY(STD_ID),
	STD_NAME VARCHAR(50) NOT NULL

)
GO

CREATE TABLE FACULTY (
		F_ID INT NOT NULL CONSTRAINT pkFacultyID  PRIMARY KEY(F_ID),
		F_NAME VARCHAR(50)  
)
GO

CREATE TABLE LEARNING 
(
		STD_ID INT CONSTRAINT fkForignKEyStd_ID FOREIGN KEY  REFERENCES dbo.STUDENT(STD_ID),
		F_ID INT CONSTRAINT fkForignKEYF_ID FOREIGN KEY REFERENCES dbo.FACULTY(F_ID)
)

SElect * FROM STUDENT
SElect * FROM FACULTY
SElect * FROM LEARNING
NAME
SELECT STD_NAME ,F_NAME FROM STUDENT JOIN FACULTY ON (STUDENT.STD_ID=FACULTY.F_ID) JOIN LEARNING ON(LEARNING.STD_ID=FACULTY.F_ID)

SELECT STD_NAME,F_NAME FROM STUDENT JOIN LEARNING ON STUDENT.STD_ID=LEARNING.STD_ID  JOIN FACULTY ON FACULTY.F_ID=LEARNING.F_ID   

SELECT COUNT(STD_ID),F_NAME FROM FACULTY  JOIN LEARNING ON FACULTY.F_ID=LEARNING.F_ID GROUP BY F_NAME


SELECT F_NAME FROM FACULTY JOIN LEARNING ON FACULTY.F_ID=LEARNING.F_ID GROUP BY F_NAME HAVING COUNT(STD_ID)>2

WITH F_NAME_CTE(F_NAME,STD_ID)
AS 
(
	SELECT F_NAME,STD_ID FROM FACULTY JOIN LEARNING ON FACULTY.F_ID=LEARNING.F_ID
)
SELECT F_NAME FROM F_NAME_CTE GROUP BY F_NAME HAVING COUNT(STD_ID)>2




ALTER PROCEDURE dbo.addData @JSON NVARCHAR(MAX)
AS

BEGIN
SET NOCOUNT ON;

DECLARE @StudenName VARCHAR(50), @FacultyName VARCHAR(50),@StudentID INT ,@FacultyID INT
DECLARE add_data CURSOR FOR 

SELECT STD_NAME,F_NAME  FROM OPENJSON(@JSON)
WITH (
    STD_NAME VARCHAR(50)  '$.NAME',
    F_NAME VARCHAR(50) '$.FNAME'
);
    
OPEN  add_data
IF @@CURSOR_ROWS>0
BEGIN
FETCH NEXT FROM add_data INTO @StudenName,@FacultyName;
WHILE @@FETCH_STATUS=0
BEGIN
SELECT @StudentID = STD_ID FROM STUDENT WHERE STD_NAME = @StudenName
SELECT @FacultyID = F_ID FROM FACULTY WHERE F_NAME = @FacultyName
INSERT INTO LEARNING VALUES(@StudentID,@FacultyID)
FETCH NEXT FROM add_data INTO @StudenName,@FacultyName;

 END
END
CLOSE add_data
DEALLOCATE add_data

 SET NOCOUNT OFF
END

DECLARE @JSON NVARCHAR(MAX); 
SET @JSON=N'[{"NAME:"D","FNAME":"Y"},
            {"NAME":"c","FNAME":"Z"}]'
EXEC dbo.addData @JSON



/*SELECT * FROM OPENJSON(@JSON)
WITH (
	STD_NAME VARCHAR(50)  '$.NAME',
	FNAME VARCHAR(50) '$.FNAME'
);*/



	
