CREATE DATABASE AssignmentDay25
GO

CREATE TABLE Employees(
	EmpId INT CONSTRAINT PKEmpId PRIMARY KEY IDENTITY,
	EmpName VARCHAR(50) NOT NULL,
	Commission INT NOT NULL,
)
GO

CREATE TABLE Inventory(
	CarId INT CONSTRAINT PKCarId PRIMARY KEY IDENTITY,
	CarName VARCHAR(50) NOT NULL,
	CarType VARCHAR(50) NOT NULL,
	NumberOfCar INT NOT NULL,
)
GO

CREATE TABLE Sales(
	SaleId INT CONSTRAINT PKSaleId PRIMARY KEY IDENTITY,
	SaleDate Date NOT NULL,
	SaleEmpId INT CONSTRAINT FKSEmpId FOREIGN KEY REFERENCES Employees(EmpId),
	SaleCarId INT CONSTRAINT FKSCarId FOREIGN KEY REFERENCES Inventory(CarId),
	NumberOfSale INT NOT NULL,
)
GO