SELECT *FROM Employees
-------------------------------ASSIGNMENT 1 --------------------------------
SELECT EmployeeID,FirstName,LastName,'DepartmentName'=	
CASE DepartmentID
		WHEN '90' THEN 'BANK DEPT'
		WHEN '60' THEN 'INSAURANCE DEPT'
		WHEN '100'THEN 'SERVICE DEPT'
END
FROM EMPLOYEES

------------------------------- ASSIGNMET 2 ---------------------------------
DECLARE @DATA NVARCHAR(MAX)= N'[
	{"STUDENTDATA":{"NAME": "HARSHIT", "ADDRESS":"VADAJ", "CITY":"AHMEDABAD", "DOB":"09/09/1999","STANDARD":"10TH"}},
	{"STUDENTDATA":{"NAME": "JIGAR", "ADDRESS":"RANIP", "CITY":"AHMEDABAD", "DOB":"07/08/1998","STANDARD":"11TH"}},
	{"STUDENTDATA":{"NAME": "PARTH", "ADDRESS":"MANINAGAR", "CITY":"AHMEDABAD", "DOB":"06/09/2000","STANDARD":"11TH"}},
	{"STUDENTDATA":{"NAME": "PARESH", "ADDRESS":"BOPAL", "CITY":"AHMEDABAD", "DOB":"06/07/1999","STANDARD":"9TH"}},
	{"STUDENTDATA":{"NAME": "JOHN", "ADDRESS":"NARODA", "CITY":"AHMEDABAD", "DOB":"05/5/2000","STANDARD":"10TH"}}
	
]'

SELECT * into json from OPENJSON( @DATA)
WITH(
		NAME VARCHAR(200)			'$.STUDENTDATA.NAME',
		ADDRESS VARCHAR(200)		'$.STUDENTDATA.ADDRESS',
		CITY VARCHAR(200)			'$.STUDENTDATA.CITY',
		DOB VARCHAR(50)				'$.STUDENTDATA.DOB',
		STANDARD VARCHAR(30)		'$.STUDENTDATA.STANDARD'
)

SELECT * FROM json
