SELECT * FROM Employees ORDER BY SALARY 
DECLARE update_salary CURSOR FOR
SELECT EmployeeID, SALARY FROM Employees


OPEN update_salary

FETCH NEXT FROM update_salary;

UPDATE  Employees
SET SALARY =CASE WHEN SALARY BETWEEN  2000 AND 7000 THEN SALARY +3000
				 WHEN SALARY BETWEEN 10000 AND 15000 THEN SALARY+5000
	             WhEN SALARY BETWEEN 20000 AND 30000 THEN SALARY +7000
				 ELSE Salary
	   END
	   CLOSE update_salary
Select * FROM Employees ORDER BY Salary




