USE [AdventureWorks2012]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [ClusteredIndex-20210314-114907]    Script Date: 3/14/2021 11:50:04 AM ******/
CREATE CLUSTERED INDEX [ClusteredIndex-20210314-114907] ON [dbo].[Sales]
(
	[Country] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


