/*USE tempdb
GO;
CREATE TABLE DEPOSIT (DEPOSIT INT);
CREATE TABLE CREDIT(CREDIT INT);
GO;

DECLARE @Payment Varchar

BEGIN TRANSACTION @Payment
DECLARE @AMOUNT*/





CREATE TABLE ACCOUNTS(
ACC_NO	INT PRIMARY KEY,
BALANCE FLOAT DEFAULT 0
);
INSERT INTO ACCOUNTS VALUES(101,48000);
INSERT INTO ACCOUNTS VALUES(684,51000);
INSERT INTO ACCOUNTS (ACC_NO)VALUES(547);

SELECT * FROM ACCOUNTS

CREATE TABLE ACC_ACTIVITY
(
	ACT_NO INT NOT NULL,
	AMOUNT FLOAT NOT NULL,
	TRANSACTION_TIME DATETIME,
	REMARKS VARCHAR(10)

);

BEGIN
	UPDATE ACCOUNTS SET BALANCE=BALANCE -2000 WHERE ACC_NO	=684;

	UPDATE ACCOUNTS SET BALANCE = BALANCE+2000 WHERE ACC_NO =547;

	INSERT INTO ACC_ACTIVITY VALUES(101,2000,GETDATE(),'DR');
	
	INSERT INTO ACC_ACTIVITY VALUES(547,2000,GETDATE(),'CR')
	COMMIT;
	PRINT ('FUND TRNSFERED SUCCESSFULLY	')
	END;

	SELECT * FROM ACC_ACTIVITY