USE [Learning]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [NonClusteredIndex-20210313-151903]    Script Date: 13-03-2021 15:19:37 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210313-151903] ON [dbo].[Employees]
(
	[FirstName] ASC,
	[PhoneNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


