USE [AdventureWorks2019]
GO

/****** Object:  Index [NonClusteredIndex-20210313-150108]    Script Date: 13-03-2021 15:21:19 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210313-150108] ON [HumanResources].[Employee]
(
	[BirthDate] ASC,
	[HireDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


