USE Day1_practice

CREATE TABLE Jobs
(	
	JobID INT NOT NULL CONSTRAINT PKJobid PRIMARY KEY IDENTITY,
	JobName VARCHAR(20)
)
CREATE TABLE Departments
(	
	DeptID INT NOT NULL CONSTRAINT PKDeptid PRIMARY KEY IDENTITY,
	DeptName VARCHAR(20)
)

CREATE TABLE Employees
(
	EmpID INT NOT NULL CONSTRAINT PKEmpid PRIMARY KEY IDENTITY,
	FirstName VARCHAR(20),
	LastName VARCHAR(20),
	Email VARCHAR(30),
	PhoneNumber NUMERIC(20),
	Hire_Date DATE,
	JobID INT CONSTRAINT FKJobs FOREIGN KEY REFERENCES Jobs(JobID),
	DeptID INT CONSTRAINT FKDepartments FOREIGN KEY REFERENCES Departments(DeptID)  
)

SELECT * FROM Employees




