CREATE TABLE Jobs
(
	JobID INT NOT NULL CONSTRAINT PKJobID PRIMARY KEY IDENTITY,
	JobTitle VARCHAR(20),
	MinSalary MONEY,
	MaxSalary MONEY NOT NULL CHECK (MaxSalary BETWEEN 0 AND 8000)
)

SELECT * from Jobs

DROP TABLE Jobs