USE Housing_Project

CREATE SCHEMA Services;


CREATE TABLE USER_Register(
		USER_ID INT CONSTRAINT pkUSER_ID PRIMARY KEY(USER_ID),
		NAME VARCHAR(50) NOT NULL,
		GENDER VARCHAR(6) NOT NULL,
		CITY   VARCHAR(20) NOT NULL,
		ADDRESS VARCHAR(100) NOT NULL,
		USER_TYPE VARCHAR(12) NOT NULL,
		PHONE_NO INT NOT NULL,
		EMAIL  VARCHAR(25) NOT NULL,
		PASSWORD VARCHAR(18) NOT NULL
)

CREATE TABLE PROPERTY(

	PROPERTY_ID INT CONSTRAINT pkPROPERTY_ID PRIMARY KEY(PROPERTY_ID),
	PROPERTY_NAME VARCHAR(18),
	PROPERTY_TYPE VARCHAR(10),
	HOUSE_NO VARCHAR(18),
	USER_ID INT CONSTRAINT fkUSERFORPROPERTY FOREIGN KEY REFERENCES dbo.USER_REGISTER(USER_ID),
)

CREATE TABLE PAYMENT(
	PAYMENT_ID INT constraint pkPAYMENT_ID PRIMARY KEY,
	USER_ID INT CONSTRAINT fkUSERPAYMENT FOREIGN KEY REFERENCES dbo.USER_REGISTER(USER_ID),
	PROPERTY_ID INT CONSTRAINT fk_ID_FOR_PROPERTYDETAILS FOREIGN KEY REFERENCES dbo.PROPERTY(PROPERTY_ID),
	PAYMENT_TYPE VARCHAR(18),
	ACC_NO INT NOT NULL,
	DEBIT_CARD_NO INT ,
	PAYMENT_date DATE,
	AMOUNT MONEY NOT NULL
)

CREATE TABLE PROPERTY_RENT (
	PROPERTY_RENT_ID INT CONSTRAINT pkRENTID PRIMARY KEY,
	USER_ID INT CONSTRAINT fk_USER_FOR_AGGREMENT FOREIGN KEY REFERENCES dbo.USER_REGISTER(USER_ID),
	TENANT_NAME VARCHAR(20),
	OWNER_NAME VARCHAR(20),
	PROPERTY_ID INT CONSTRAINT fk_ID_FOR_PROPERTRENTYDETAILS FOREIGN KEY REFERENCES dbo.PROPERTY(PROPERTY_ID),
	IFSC_CODE VARCHAR(20),
	BANK_ACC_NO INT NOT NULL,
	PAN_NO VARCHAR(20),
	PAYMENT_ID INT CONSTRAINT fkPAYMENTDETAILSAGREEMNT FOREIGN KEY REFERENCES dbo.PAYMENT(PAYMENT_ID)
	
)

CREATE TABLE RENT_AGGREMENT(
	AGREEMENT_ID INT CONSTRAINT pkAGREEMENT_ID PRIMARY KEY(AGREEMENT_ID),
	USER_ID INT CONSTRAINT fk_USER_FORRENTCONSTRAINTAGGREMENT FOREIGN KEY REFERENCES dbo.USER_REGISTER(USER_ID),
	PAYMENT_ID INT CONSTRAINT fkPAYMENTDETAILSAGREEMNTFORRENT FOREIGN KEY REFERENCES dbo.PAYMENT(PAYMENT_ID),
	PROPERTY_ID INT CONSTRAINT fk_ID_FOR_RENT_AGGREMENTDETAILS FOREIGN KEY REFERENCES dbo.PROPERTY(PROPERTY_ID), 
	OWNER_NAME VARCHAR(20) NOT NULL,
	PERMANENT_ADDRESS_OF_OWNERE VARCHAR(30) NOT NULL,
	OWNER_EMAIL_ID VARCHAR(25),
	AGGREMENT_DATE DATE,

)

CREATE TABLE Services.Packers_and_Movers(
		ID  INT CONSTRAINT pkPACKETANIMOVERS PRIMARY KEY(ID),
		USER_ID INT CONSTRAINT fk_USER_FOR_PACKER_MOVERS FOREIGN KEY REFERENCES dbo.USER_REGISTER(USER_ID),
		DATE_OF_MOVEMENT DATE,
		PARTERNER_COMPANY_NAME	VARCHAR(18),
		COMPANY_EMAIL_ID VARCHAR(25),
		BUDGET MONEY,
		CITY_MOVE_FROM VARCHAR(15),
		HOUSE_TYPE VARCHAR(18)
)

CREATE TABLE  Services.Home_Intereor(
		ID INT CONSTRAINT pkidforHomeIntereor PRIMARY KEY, 
		USER_ID INT CONSTRAINT fk_USER_FOR_home_intereor FOREIGN KEY REFERENCES dbo.USER_REGISTER(USER_ID),
		HOUSE_TYPE VARCHAR(20),
		SCOPE_OF_WORK	VARCHAR(20),
		Possetion_Date	DATE,
		VENDOR VARCHAR(20),
		CITY VARCHAR(20),
		BUDGET MONEY,
)

CREATE TABLE Services.LoanDetails(
	LOAN_ID INT CONSTRAINT pkLOANPRIMARYKEY PRIMARY KEY,
	USER_ID INT CONSTRAINT fk_USER_FOR_Loandetails FOREIGN KEY REFERENCES dbo.USER_REGISTER(USER_ID),
	MONTHLY_INCOME MONEY ,
	LOAN_AMOUNT MONEY,
	PROFESSION VARCHAR(18),

)

CREATE TABLE SERVICES.ROOFTOPDetails(
	ROOF_ID INT CONSTRAINT pkROOFID  PRIMARY KEY,
	USER_ID INT CONSTRAINT fk_USER_FOR_Rooftop FOREIGN KEY REFERENCES dbo.USER_REGISTER(USER_ID),
	HOUSE_TYPE VARCHAR(18),
	CITY VARCHAR(18),
	COMMENTS VARCHAR(50)
)

CREATE TABLE SERVICES.RENT_FURNITURE(
	RENT_FURNITURE_ID INT CONSTRAINT pkRENT_FURNITURE_ID PRIMARY KEY,
	USER_ID INT CONSTRAINT fk_USER_FOR_rent_furniture FOREIGN KEY REFERENCES dbo.USER_REGISTER(USER_ID),
	CITY_CHOSENE VARCHAR(20),
	ADDRESS_TO_STAY VARCHAR(20),
	PROFESSION VARCHAR(20),
	COMMENT VARCHAR(50)
)



