const student = [
    {
      img:"https://randomuser.me/api/portraits/thumb/men/11.jpg",
      logo:"GTU.png",
      ID:1,
      FirstName:"Bhargav",
      LastName:"Modi",
      DOB:"20/12/1998",
      CollegeName:"GEC",
      Address:"Patan"
    },
    {
      img:"https://randomuser.me/api/portraits/thumb/men/12.jpg",
      logo:"NIT.png",
      ID:2,
      FirstName:"Rohit",
      LastName:"Sharma",
      DOB:"10/05/2001",
      CollegeName:"LD",
      Address:"Ahemdabad"
     },
     {
       img:"https://randomuser.me/api/portraits/thumb/men/13.jpg",
       logo:"IIT.png",
       ID:3,
       FirstName:"Mohit",
       LastName:"Raval",
       DOB:"15/02/1999",
       CollegeName:"NIT",
       Address:"Surat"
     },
     {
       img:"https://randomuser.me/api/portraits/thumb/men/14.jpg",
       logo:"GTU.png",
       ID:4,
       FirstName:"Amit",
       LastName:"Soni",
       DOB:"20/01/2000",
       CollegeName:"GEC",
       Address:"Modasa"
     },
     {
       img:"https://randomuser.me/api/portraits/thumb/men/15.jpg",
       logo:"GTU.png",
       ID:5,
       FirstName:"Sani",
       LastName:"Modi",
       DOB:"20/01/1990",
       CollegeName:"IIT",
       Address:"Rajkot"
     }
  ]

export default student   