const mongoose=require('mongoose');
const Schema=mongoose.Schema;

const EmployeeSchema=new Schema({
    EmpId:{
        type:Number
    },
    AddressLine1:{
        type:String
    },
    AddressLine2:{
        type:String
    },
    AddressLine3:{
        type:String
    },
    assignments:{
        type:[Number]
    },
    CitizenshipId:{
        type:String
    },
    City:{
        type:String
    },
    Country:{
        type:String
    },
    DateOfBirth:{
        type:String
    },
    DriversLicenseExpirationDate:{
        type:String
    },
    DriversLicenseId:{
        type:String
    },
    DriversLicenseIssuingCountry:{
        type:String
    },
    FirstName:{
        type:String
    },
    Gender:{
        type:String
    },
    HireDate:{
        type:String
    },
    HomePhoneCountryCode:{
        type:String
    },
    HomePhoneNumber:{
        type:String
    },
    LastName:{
        type:String
    },
    LastUpdateDateTime:{
        type:String
    },
    MaritalStatus:{
        type:String
    },
    MiddleName:{
        type:String
    }
});

module.exports = Employee = mongoose.model('employee',EmployeeSchema);