CREATE TABLE CARS
	(CAR_ID INT NOT NULL,
	VIN INT PRIMARY KEY NOT NULL,
	MAKE VARCHAR(15) NOT NULL,
	MODEL VARCHAR(15),
	C_YEAR DATE NOT NULL,
	MILEAGE INT,
	ASK_PRICE DECIMAL(10,0),
	INVOICE_PRICE DECIMAL(10,0)
	)

CREATE TABLE DEALERSHIPS
	(DEALERSHIP_ID INT PRIMARY KEY NOT NULL ,
	D_NAME VARCHAR(25) NOT NULL,
	D_ADDRESS VARCHAR(25),
	D_CITY VARCHAR(15),
	D_STATE VARCHAR(15)
	)

CREATE TABLE SALESPERSONS
	(SALESPERSON_ID INT PRIMARY KEY NOT NULL,
	S_NAME VARCHAR(20) 
	)

CREATE TABLE CUSTOMERS
	(CUSTOMER_ID INT PRIMARY KEY NOT NULL,
	C_NAME VARCHAR(20) NOT NULL,
	C_ADDRESS VARCHAR(25),
	C_CITY VARCHAR(15),
	C_STATE VARCHAR(15)
	)

CREATE TABLE REPORTSTO
	(REPORTSTO_ID INT NOT NULL,
	SALESPERSON_ID INT,
	DEALERSHIP_ID INT,
	MANAGING_SALES_PERSON_ID INT NOT NULL
	)

CREATE TABLE WORKSATS
	(WORKSAT_ID INT NOT NULL,
	SALESPERSON_ID INT,
	DEALERSHIP_ID INT,
	MONTH_WORKED INT,
	BASE_SALARY_FOR_MONTH INT
	)

CREATE TABLE INVENTORIES
	(INVENTORY_ID INT NOT NULL,
	VIN INT,
	DEALERSHIP_ID INT
	)
CREATE TABLE SALES
	(SALES_ID INT NOT NULL,
	CUSTOMER_ID INT,
	SALESPERSON_ID INT,
	DEALERSHIP_ID INT,
	SALES_PRICE DECIMAL(10,0),
	SALE_DATE DATE
	)


SELECT S.S_NAME FROM SALESPERSONS S LEFT JOIN WORKSATS W ON S.SALESPERSON_ID=W.SALESPERSON_ID
GO

SELECT C_NAME,C_ADDRESS,C_CITY FROM CUSTOMERS WHERE C_CITY LIKE 'AHMEDABAD'
GO

SELECT VIN,MAKE,MODEL,C_YEAR,MILEAGE FROM CARS