select * from Employees

WITH EMP_CTE(SRANK, SALARY,FIRSTNAME)
AS
(
SELECT RANK() OVER( ORDER BY SALARY DESC),Salary,FirstName FROM Employees 
)
SELECT * FROM EMP_CTE
GO

WITH EMP_CTE(EMLPLOYEEID, FIRSTNAME,SALARY, SRANK)
AS
(
SELECT * FROM(SELECT  EmployeeID, FirstName, Salary,
	ROW_NUMBER() OVER (ORDER BY SALARY DESC)RANK FROM Employees) Employees WHERE RANK=4
)
SELECT * FROM EMP_CTE
GO

WITH EMP_CTE(SRANK,SALARY)
AS
(
	SELECT DENSE_RANK() OVER (ORDER BY SALARY DESC),Salary FROM Employees
)
SELECT * FROM EMP_CTE
GO

WITH EMP_CTE(SUM_SALARY,DEPARTMENT_ID)
AS
(
	SELECT SUM(SALARY),DepartmentID FROM Employees GROUP BY DepartmentID
)
SELECT * FROM EMP_CTE
GO

WITH EMP_CTE(TOTAL_SALARY,DEPARTMENT_ID)
AS
(
	SELECT SUM(SALARY) AS TOTAL_SALARY,DepartmentID FROM Employees GROUP BY DepartmentID 
)
SELECT TOTAL_SALARY,DEPARTMENT_ID FROM EMP_CTE
ORDER BY TOTAL_SALARY DESC
GO

WITH EMP_CTE(MAX_SALARY,DEPARTMENT_ID)
AS
(
	SELECT MAX(SALARY) AS TOTAL_SALARY,DepartmentID FROM Employees GROUP BY DepartmentID 
)
SELECT MAX_SALARY,DEPARTMENT_ID FROM EMP_CTE
ORDER BY MAX_SALARY ASC
GO

WITH EMP_CTE(MIN_SALARY,DEPARTMENT_ID)
AS
(
	SELECT MIN(SALARY) AS TOTAL_SALARY,DepartmentID FROM Employees GROUP BY DepartmentID 
)
SELECT MIN_SALARY,DEPARTMENT_ID FROM EMP_CTE
ORDER BY MIN_SALARY ASC
GO


WITH EMP_CTE(TOTAL_SALARY,DEPARTMENT_ID)
AS
(
	SELECT SUM(SALARY) AS TOTAL_SALARY,DepartmentID FROM Employees GROUP BY DepartmentID HAVING  SUM(SALARY)>50000 
)
SELECT TOTAL_SALARY,DEPARTMENT_ID FROM EMP_CTE
ORDER BY TOTAL_SALARY
GO





